name: flutter_hrms
description: 毕业设计项目：企业人事管理信息系统

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.12.0
  marquee: ^1.3.1
  get_it: ^1.0.3+2
  tree_view: ^0.0.5
  event_bus: ^1.1.0
  url_launcher: ^5.0.3
  connectivity: ^0.4.6+1
  cupertino_icons: ^0.1.2
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/header.jpg
    - assets/images/man.png
    - assets/images/woman.png
    - assets/images/department.png